export const PERMISSIONS = {
  PRODUCTS_VIEW: 'PRODUCTS_VIEW',
  PRODUCTS_MANAGE: 'PRODUCTS_MANAGE',
  SUPPLIERS_VIEW: 'SUPPLIERS_VIEW',
  SUPPLIERS_MANAGE: 'SUPPLIERS_MANAGE',
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_MANAGE: 'PURCHASES_MANAGE',
  PURCHASES_RECEIVE: 'PURCHASES_RECEIVE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',
  USERS_MANAGE: 'USERS_MANAGE',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
