export const PERMISSIONS = {
  PRODUCTS_VIEW: 'PRODUCTS_VIEW',
  PRODUCTS_MANAGE: 'PRODUCTS_MANAGE',
  SUPPLIERS_VIEW: 'SUPPLIERS_VIEW',
  SUPPLIERS_MANAGE: 'SUPPLIERS_MANAGE',
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_MANAGE: 'PURCHASES_MANAGE',
  PURCHASES_RECEIVE: 'PURCHASES_RECEIVE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',
  USERS_MANAGE: 'USERS_MANAGE',
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_MANAGE: 'CUSTOMERS_MANAGE',
  CUSTOMERS_EXPORT: 'CUSTOMERS_EXPORT',
  DISTRIBUTION_VIEW: 'DISTRIBUTION_VIEW',
  DISTRIBUTION_MANAGE: 'DISTRIBUTION_MANAGE',
  DISTRIBUTION_TRACK: 'DISTRIBUTION_TRACK',
  DISTRIBUTION_EVIDENCE: 'DISTRIBUTION_EVIDENCE',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
