export const PERMISSIONS = {
  USERS_MANAGE: 'USERS_MANAGE',
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_MANAGE: 'CUSTOMERS_MANAGE',
  CUSTOMERS_EXPORT: 'CUSTOMERS_EXPORT',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
